### ISSUE TITLE
native-basic-auth

### ISSUE THREAD

**Issue by stenote** [rekcod/docker-registry#1]
https://github.com/docker/distribution/blob/master/docs/deploying.md#native-basic-auth

貌似没必要专门用 nginx 做 basic auth

**Comment by m31271n** [comment]
**使用 Nginx 做反向代理的原因：**想让 registry 也使用 443 端口，如果不用 Nginx 做反向代理，registry 倘若占用了 443 端口，其他的服务就不能使用 443 端口了。

**使用 Nginx 的 Auth 的原因：**既然已经用了 Nginx，就让 Registry 提供纯粹的镜像托管服务，验证等内容交给 Nginx 就好了。

**Comment by stenote** [comment]
Good Job
