### ISSUE TITLE
get-a-certificate

### ISSUE THREAD

**Issue by stenote** [rekcod/docker-registry#2]
https://github.com/docker/distribution/blob/master/docs/deploying.md#get-a-certificate

distribution 也支持 certificate。nginx 进行 ssl 证书验证也可以考虑直接交给 distribution

**Comment by m31271n** [comment]
这个问题和上个问题一致。可以看 standalone 分支。

**Comment by m31271n** [comment]
其实我只是想让 Registry 可以和其他服务一起共用 443 端口。

**Comment by stenote** [comment]
Good Job ! standalone 中，5000 做 修改为 443 端口？

**Comment by stenote** [comment]
既然 standalone 了，直接 -p 443:5000 是不是更好一点？

“不谈计量谈毒性，都是耍流氓”。 “不谈场景谈设计，都是耍流氓”。 Close ！

**Comment by m31271n** [comment]
如果服务器上只有这一个服务，那随便什么端口了。这里只是想给个 standalone 的通用方案。算是抛砖引玉了。
